# Generated by Django 5.2.4 on 2026-04-15 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/logo/')),
                ('primary_color', models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='Primary color must be a valid hex color like #0F172A.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
            },
        ),
    ]
