# Generated by Django 5.2.4 on 2026-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('card', 'Card'), ('cash', 'Cash')], default='whatsapp', max_length=20),
        ),
    ]
