# Generated by Codex on 2026-04-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_order_is_paid_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("customer", "Customer")], default="customer", max_length=20)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["full_name", "user__username"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to=settings.AUTH_USER_MODEL),
        ),
    ]
